#!/usr/bin/env python3
"""Generate frontend TypeScript types from the Pydantic dashboard boundary."""

from __future__ import annotations

import argparse
from pathlib import Path

from waterfallhunter.core.dashboard_stream import (
    DashboardSnapshot,
    DashboardStreamEvent,
)


DEFAULT_OUTPUT = Path("frontend/generated/dashboard-contract.ts")


def _literal(schema: dict, field: str) -> str:
    value = schema["properties"][field]["const"]
    return f'"{value}"'


def render_types() -> str:
    snapshot = DashboardSnapshot.model_json_schema()
    event = DashboardStreamEvent.model_json_schema()
    snapshot_contract = _literal(snapshot, "contract_version")
    snapshot_schema = _literal(snapshot, "schema_version")
    event_contract = _literal(event, "contract_version")
    return f'''// Generated by scripts/generate_dashboard_types.py. Do not edit manually.
export type JsonObject = Record<string, unknown>;

export interface DashboardSnapshot {{
  contract_version: {snapshot_contract};
  schema_version: {snapshot_schema};
  snapshot_version: number;
  generated_at: number;
  state: "READY";
  total: number;
  candidates: Record<string, JsonObject>;
  final_ranking: JsonObject;
  signal_funnel: JsonObject;
}}

export interface DashboardStreamEvent {{
  contract_version: {event_contract};
  event_id: string;
  event_type: "snapshot" | "heartbeat";
  snapshot_version: number;
  schema_version: {snapshot_schema};
  generated_at: number;
  last_event_id: string | null;
  payload_hash: string;
  payload: DashboardSnapshot | null;
  replayed: boolean;
  full_snapshot: boolean;
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_types(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
