#!/usr/bin/env python3
"""Generate frontend TypeScript types from the Pydantic dashboard boundary."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from waterfallhunter.core.dashboard_stream import (
    DashboardSnapshot,
    DashboardStreamEvent,
)


DEFAULT_OUTPUT = Path("frontend/generated/dashboard-contract.ts")


def _typescript_type(schema: dict) -> str:
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(_typescript_type(option) for option in schema["anyOf"])
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    schema_type = schema.get("type")
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "string":
        return "string"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        items = schema.get("items")
        if not isinstance(items, dict):
            raise ValueError(f"dashboard array schema missing items: {schema!r}")
        return f"{_typescript_type(items)}[]"
    if schema_type == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            value_type = (
                "JsonObject"
                if additional.get("type") == "object"
                else _typescript_type(additional)
            )
            return f"Record<string, {value_type}>"
        return "JsonObject"
    raise ValueError(f"unsupported dashboard JSON Schema property: {schema!r}")


def _interface(name: str, schema: dict) -> str:
    required = set(schema.get("required", ()))
    lines = [f"export interface {name} {{"]
    for field, property_schema in schema["properties"].items():
        optional = "" if field in required else "?"
        lines.append(f"  {field}{optional}: {_typescript_type(property_schema)};")
    lines.append("}")
    return "\n".join(lines)


def render_types() -> str:
    snapshot = DashboardSnapshot.model_json_schema()
    event = DashboardStreamEvent.model_json_schema()
    definitions: dict[str, dict] = {}
    definitions.update(snapshot.get("$defs", {}))
    definitions.update(event.get("$defs", {}))
    definitions.pop("DashboardSnapshot", None)
    definition_interfaces = [
        _interface(name, schema)
        for name, schema in sorted(definitions.items())
        if schema.get("type") == "object" and "properties" in schema
    ]
    snapshot_interface = _interface("DashboardSnapshot", snapshot)
    event_interface = _interface("DashboardStreamEvent", event)
    blocks = [
        "// Generated by scripts/generate_dashboard_types.py. Do not edit manually.",
        "export type JsonObject = Record<string, unknown>;",
        *definition_interfaces,
        snapshot_interface,
        event_interface,
    ]
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_types(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
